#!/usr/bin/env bash

set -eu -o pipefail

echo
echo "Installing gems locally"
echo "= = ="
echo

ruby_api_version=$(ruby -rrbconfig -e "puts RbConfig::CONFIG['ruby_version']")

if [ -d gems ]; then
  rm -rf gems

  echo "Removed previously installed gems"
  echo
fi

cmd="gem install --force --pre --no-document --install-dir ./gems/ruby/$ruby_api_version --bindir ./gems/bin --no-user-install test_bench"

echo $cmd
($cmd)

echo

rm -vf install-gems-installation.gem

ruby <<RUBY > ./gems/gems_init.rb
puts "# Generated by $0\n\n"
Dir['gems/ruby/$ruby_api_version/gems/*'].each do |dir|
  dir = File.basename(dir)
  puts "\$LOAD_PATH.push(File.join(__dir__, 'ruby', '$ruby_api_version', 'gems', '#{dir}', 'lib'))"
end
RUBY

echo "Wrote ./gems/gems_init.rb"

for bin in ./gems/bin/*; do
  get_bin_path_rb=$(sed -n -E "s/^load (Gem\.activate_bin_path\('[^']+', '[^']+'), version\)$/\1)/p" $bin)

  get_relative_path_rb="puts Pathname($get_bin_path_rb).relative_path_from(File.expand_path('gems/bin'))"

  relative_path=$(GEM_PATH=./gems/ruby/$ruby_api_version ruby -r rubygems -r pathname -e "$get_relative_path_rb")

  cat > $bin <<TEXT
#!/usr/bin/env ruby
require_relative '../gems_init'
load File.expand_path('$relative_path', __dir__)
TEXT
  chmod 755 $bin

  echo "Wrote executable: $bin"
done

echo
echo "(done)"
echo "- - -"
echo
