#!/usr/bin/env bash

set -eEuo pipefail

echo
echo "Installing gems locally"
echo "= = ="

if [ -z ${POSTURE+x} ]; then
  echo "(POSTURE is not set. Using \"operational\" by default.)"
  posture="operational"
else
  posture=$POSTURE
fi

gem_dir="./gems"

repo_name=$(basename $PWD)
gemspec=$(ls -A *.gemspec | grep ${repo_name//-/.} || true)

if [ -z "$gemspec" ]; then
  echo "No gemspec found: ${repo_name//-/*}.gemspec"
  exit 1
fi

gem_info=($(
  gem build $gemspec --output install-gems.gem --quiet 2>/dev/null |
    sed -E -n 's/^[[:blank:]]*(Name|Version):[[:blank:]]*(.*)$/\2/p'
))
gem_name=${gem_info[0]}
gem="$gem_name-${gem_info[1]}"

install_dir="$gem_dir/ruby/$(ruby -rrbconfig -e "puts RbConfig::CONFIG['ruby_version']")"

echo "Posture: $posture"
echo "Gem Directory: $gem_dir"
echo "Gemspec: $gemspec"

echo
echo "Removing installed gems"
echo "- - -"

cmd="rm -rf $gem_dir"

echo $cmd
($cmd)

echo
echo "Installing gems"
echo "- - -"

gem_args="--install-dir $install_dir --bindir ./gems/bin --no-user-install"

cmd="gem install --force $gem_args install-gems.gem"
if [ operational != "$posture" ]; then
  cmd="$cmd --development"
fi
echo $cmd
($cmd)
echo

cmd="gem uninstall --executables $gem_args $gem_name"
echo $cmd
($cmd)
echo

rm -vf install-gems.gem
echo

mkdir -p x
rm -f x/*

ruby -rrubygems -rpathname <<RUBY
File.open('gems/gems_init.rb', 'w') do |gems_init_rb|
  gems_init_rb.puts "# Generated by $0\n\n"

  Dir['$install_dir/specifications/*.gemspec'].each do |gemspec|
    spec = Gem::Specification.load(gemspec)

    spec.full_require_paths.each do |full_require_path|
      require_path = Pathname(full_require_path).relative_path_from(Dir.pwd)

      gems_init_rb.puts "\$LOAD_PATH.push('#{require_path}')"
    end

    spec.executables.each do |executable|
      executable_path =  Pathname(spec.bin_file(executable)).relative_path_from(Dir.pwd).to_s

      File.open("x/#{executable}", 'w') do |executable|
        executable.write(<<-RUBY)
#!/usr/bin/env ruby
#
# Generated by install-gems.sh

require_relative '../gems/gems_init'

load File.expand_path('#{File.join('..', executable_path)}', __dir__)
        RUBY

        File.chmod(0755, executable.path)

        puts "Wrote executable: #{executable.path} (#{spec.name})"
      end
    end
  end

  puts "Wrote #{gems_init_rb.path}"
end
RUBY

echo
echo "(done)"
echo "- - -"
echo
